[package]
name = "epiphyte"
edition = "2024"
authors = ["rafky alfarrakhan <muhammad.rafky@amartha.com>"]

[dependencies]
axum = { version = "0.8.4", features = ["json"] }
clap = { version = "4.5.48", features = ["derive"] }
cli-table = "0.5.0"
console = "0.16.2"
dll-syringe = { version = "0.16.0", features = ["rpc-core", "rpc-raw"] }
object = "0.37.3"
scopeguard = "1.2.0"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.143"
time = "0.3.47"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = [
    "fmt",
    "local-time",
    "time",
] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

[workspace]
members = ["example"]
resolver = "3"

[profile.release]
lto = true
