name: Release

on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: windows-2022
        permissions: write-all
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Build
              run: cargo build --release --verbose
            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
            - name: Upload epiphyte.exe
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: target/i686-pc-windows-msvc/release/epiphyte.exe
                  asset_name: epiphyte-${{ github.ref_name }}.exe
                  asset_content_type: application/vnd.microsoft.portable-executable
